name: Add Action
on:
 push:
   branches:
     - GX-9114-✅-challenge-technical-exercise-qa-automation-engineer-in-cypress
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
